version: '3'

services:
  docker-registry:
    container_name: docker-registry
    image: registry:2.8.1
    ports:
      - "${DOCKER_REGISTRY_HOST_PORT}:5000"
    volumes:
      - /var/lib/registry 
  git-server:
    build:
      context: ./git-server
      args:
        GOGS_VERSION: ${GOGS_VERSION}
        APP_TIMEZONE: ${APP_TIMEZONE}
    depends_on:
      - gogs-db
    ports:
      - "${GOGS_GIT_SERVER_HOST_PORT}:3000"
      - "9022:22"
    volumes:
      - gogs_data:${GOGS_DATA_DIR}
      - gogs_logs:${GOGS_LOGS_DIR}

  jenkins:
    container_name: jenkins
    build: ./jenkins
    ports:
      - '${JENKINS_HOST_PORT}:8080'
      - '8443:8443'
      - '50000:50000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/jenkins_home

  gogs-db:
    image: postgres:${POSTGRES_VERSION}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${POSTGRES_DATA_DIR}
    volumes:
      - gogs_db_data:${POSTGRES_DATA_DIR}

volumes:
  jenkins_data:
    driver: local
  gogs_logs:
    driver: local
  gogs_data:
    driver: local
  gogs_db_data:
    driver: local
